name: Tall Guy Woodworking Inc
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60295
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4c2915'
    - '#060604'
    - '#e5e2db'
    - '#c37541'
    - '#b2a9a0'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
