name: Tall Guy Woodworking Inc
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60295
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040605'
    - '#ffffff'
    - '#03ffff'
    - '#039066'
    - '#6c7570'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
