name: Tall Guy Woodworking Inc
favicon: null
layout_spectrum: 0.71806
typography_spectrum: 0.50064
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4d4d4'
    - '#2c2c2c'
    - '#bc7138'
    - '#d4ac6d'
    - '#949351'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6984271488618106
  rhythmicContrast: 0.622400232590735
purpose: []
